import type {
  Invoice, Contract, InsurancePolicy, Payment, Renewal, InboxAlert, AppSummary, DeliveryOrder
} from './types';

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    vendorName: 'Apex IT Solutions',
    vendorEmail: 'billing@apexit.com',
    invoiceNumber: 'APEX-2024-112',
    amount: 4750.00,
    dueDate: '2024-12-28',
    receivedDate: '2024-12-10',
    status: 'flagged',
    source: 'gmail',
    extractionConfidence: 0.97,
    contractId: 'ctr-001',
    previousAmount: 4000.00,
    lineItems: [
      { description: 'Managed IT Support (42 hrs @ $95/hr)', quantity: 42, unitPrice: 95, total: 3990, contractedPrice: 95, variance: 190, confidence: 0.98 },
      { description: 'Emergency On-site Visit', quantity: 1, unitPrice: 760, total: 760, contractedPrice: 0, variance: 760, confidence: 0.94 },
    ],
    anomalies: [
      {
        id: 'ano-001',
        type: 'contract_mismatch',
        severity: 'high',
        description: 'Invoice bills 42 hours — contract caps at 40 hrs/month. Overcharge: $190.',
        expectedValue: 4000,
        actualValue: 4750,
        percentageVariance: 18.75,
        recommendation: 'Request credit memo for 2 excess hours ($190). Flag emergency visit for pre-approval next time.',
      },
      {
        id: 'ano-002',
        type: 'price_increase',
        severity: 'medium',
        description: 'Total invoice 18.75% higher than last month ($4,000 → $4,750).',
        expectedValue: 4000,
        actualValue: 4750,
        percentageVariance: 18.75,
        recommendation: 'Review contract terms. Emergency visit may not be covered under standard agreement.',
      },
    ],
  },
  {
    id: 'inv-002',
    vendorName: 'Arctic Snow Services',
    vendorEmail: 'invoices@arcticsnow.com',
    invoiceNumber: 'ASS-2024-082',
    amount: 260.00,
    dueDate: '2024-12-20',
    receivedDate: '2024-12-13',
    status: 'flagged',
    source: 'gmail',
    extractionConfidence: 0.99,
    contractId: 'ctr-002',
    lineItems: [
      { description: 'Snow removal — Dec 12 event (4.2" claimed)', quantity: 1, unitPrice: 260, total: 260, contractedPrice: 195, variance: 65, confidence: 0.99 },
    ],
    anomalies: [
      {
        id: 'ano-003',
        type: 'duplicate',
        severity: 'high',
        description: 'Matches paid invoice ASS-2024-079 (same vendor, same amount, same date range). Do not pay.',
        recommendation: 'Contact Arctic Snow Services to void duplicate. Reference invoice ASS-2024-079.',
      },
      {
        id: 'ano-004',
        type: 'service_mismatch',
        severity: 'medium',
        description: 'Vendor claims 4.2" snowfall on Dec 12. NOAA records show 2.8" at your location. Contract rate for <3" is $195, not $260.',
        expectedValue: 195,
        actualValue: 260,
        percentageVariance: 33.3,
        recommendation: 'Dispute $65 overcharge. Attach NOAA weather report as evidence.',
      },
    ],
  },
  {
    id: 'inv-003',
    vendorName: 'Salesforce Inc.',
    vendorEmail: 'billing@salesforce.com',
    invoiceNumber: 'SF-INV-2024-1201',
    amount: 1247.00,
    dueDate: '2024-12-31',
    receivedDate: '2024-12-01',
    status: 'pending',
    source: 'gmail',
    extractionConfidence: 0.99,
    contractId: 'ctr-003',
    lineItems: [
      { description: 'Salesforce Sales Cloud — 5 seats', quantity: 5, unitPrice: 249.40, total: 1247, contractedPrice: 249.40, variance: 0, confidence: 0.99 },
    ],
    anomalies: [],
  },
  {
    id: 'inv-004',
    vendorName: 'WeWork',
    vendorEmail: 'billing@wework.com',
    invoiceNumber: 'WW-2024-DEC',
    amount: 3200.00,
    dueDate: '2025-01-01',
    receivedDate: '2024-12-05',
    status: 'pending',
    source: 'outlook',
    extractionConfidence: 0.96,
    lineItems: [
      { description: 'Private Office — 4 desks, December 2024', quantity: 1, unitPrice: 3200, total: 3200, contractedPrice: 3200, variance: 0, confidence: 0.96 },
    ],
    anomalies: [],
  },
  {
    id: 'inv-005',
    vendorName: 'Midwest Plumbing Co.',
    vendorEmail: 'admin@midwestplumbing.com',
    invoiceNumber: 'MPC-2024-441',
    amount: 0,
    dueDate: '',
    receivedDate: '2024-12-14',
    status: 'incomplete',
    source: 'gmail',
    extractionConfidence: 0.41,
    lineItems: [],
    missingFields: ['total_amount', 'due_date', 'lineItems', 'invoice_number'],
    anomalies: [
      {
        id: 'ano-005',
        type: 'incomplete',
        severity: 'medium',
        description: 'Invoice is missing total amount, due date, and itemized line items. Auto-response sent requesting details.',
        recommendation: 'Auto-response email sent Dec 14. Follow up if no response in 3 business days.',
      },
    ],
  },
  {
    id: 'inv-006',
    vendorName: 'Slack Technologies',
    vendorEmail: 'billing@slack.com',
    invoiceNumber: 'SLK-2024-ANN',
    amount: 4462.50,
    dueDate: '2025-01-15',
    receivedDate: '2024-12-15',
    status: 'pending',
    source: 'gmail',
    extractionConfidence: 0.98,
    contractId: 'ctr-004',
    lineItems: [
      { description: 'Slack Pro — 25 seats × $178.50/yr', quantity: 25, unitPrice: 178.50, total: 4462.50, contractedPrice: 178.50, variance: 0, confidence: 0.98 },
    ],
    anomalies: [],
  },
  {
    id: 'inv-007',
    vendorName: 'Apex IT Solutions',
    vendorEmail: 'billing@apexit.com',
    invoiceNumber: 'APEX-2024-098',
    amount: 4000.00,
    dueDate: '2024-11-30',
    receivedDate: '2024-11-10',
    status: 'approved',
    source: 'gmail',
    extractionConfidence: 0.97,
    contractId: 'ctr-001',
    lineItems: [
      { description: 'Managed IT Support (40 hrs @ $95/hr)', quantity: 40, unitPrice: 95, total: 3800, contractedPrice: 95, variance: 0, confidence: 0.98 },
      { description: 'Remote monitoring fee', quantity: 1, unitPrice: 200, total: 200, contractedPrice: 200, variance: 0, confidence: 0.97 },
    ],
    anomalies: [],
  },
  {
    id: 'inv-008',
    vendorName: 'Arctic Snow Services',
    vendorEmail: 'invoices@arcticsnow.com',
    invoiceNumber: 'ASS-2024-079',
    amount: 260.00,
    dueDate: '2024-12-10',
    receivedDate: '2024-12-05',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.99,
    contractId: 'ctr-002',
    lineItems: [
      { description: 'Snow removal — Dec 5 event (3.8")', quantity: 1, unitPrice: 260, total: 260, contractedPrice: 260, variance: 0, confidence: 0.99 },
    ],
    anomalies: [],
  },
];

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'ctr-001',
    vendorName: 'Apex IT Solutions',
    contractType: 'service',
    description: 'Managed IT support — 40 hrs/month + remote monitoring',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    autoRenews: true,
    renewalNoticeDays: 60,
    totalContractValue: 48000,
    billingFrequency: 'monthly',
    lineItems: [
      { description: 'Managed IT support hours', unit: 'per hour', unitPrice: 95, maxQuantity: 40 },
      { description: 'Remote monitoring fee', unit: 'monthly flat', unitPrice: 200 },
    ],
    linkedInvoiceIds: ['inv-001', 'inv-007'],
    yearOverYear: [
      { year: 2022, totalSpend: 42000, invoiceCount: 12, avgInvoiceAmount: 3500 },
      { year: 2023, totalSpend: 45600, invoiceCount: 12, avgInvoiceAmount: 3800 },
      { year: 2024, totalSpend: 48000, invoiceCount: 12, avgInvoiceAmount: 4000 },
    ],
    requiresServiceVerification: false,
    daysUntilExpiration: 18,
  },
  {
    id: 'ctr-002',
    vendorName: 'Arctic Snow Services',
    contractType: 'maintenance',
    description: 'Snow removal — per-event billing based on snowfall depth',
    startDate: '2024-11-01',
    endDate: '2025-03-31',
    autoRenews: false,
    renewalNoticeDays: 30,
    totalContractValue: 3500,
    billingFrequency: 'per_event',
    lineItems: [
      { description: 'Snow removal 1–3 inches', unit: 'per event', unitPrice: 195 },
      { description: 'Snow removal 3–6 inches', unit: 'per event', unitPrice: 260 },
      { description: 'Snow removal 6+ inches', unit: 'per event', unitPrice: 350 },
    ],
    linkedInvoiceIds: ['inv-002', 'inv-008'],
    yearOverYear: [
      { year: 2022, totalSpend: 2800, invoiceCount: 11, avgInvoiceAmount: 254 },
      { year: 2023, totalSpend: 3100, invoiceCount: 12, avgInvoiceAmount: 258 },
      { year: 2024, totalSpend: 2600, invoiceCount: 10, avgInvoiceAmount: 260 },
    ],
    requiresServiceVerification: true,
    serviceVerificationType: 'snowfall_inches',
    daysUntilExpiration: 112,
  },
  {
    id: 'ctr-003',
    vendorName: 'Salesforce Inc.',
    contractType: 'saas',
    description: 'Salesforce Sales Cloud — 5 seats annual subscription',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    autoRenews: true,
    renewalNoticeDays: 30,
    totalContractValue: 14964,
    billingFrequency: 'monthly',
    lineItems: [
      { description: 'Sales Cloud Professional — per seat', unit: 'per seat/month', unitPrice: 249.40, maxQuantity: 5 },
    ],
    linkedInvoiceIds: ['inv-003'],
    yearOverYear: [
      { year: 2022, totalSpend: 12000, invoiceCount: 12, avgInvoiceAmount: 1000 },
      { year: 2023, totalSpend: 13440, invoiceCount: 12, avgInvoiceAmount: 1120 },
      { year: 2024, totalSpend: 14964, invoiceCount: 12, avgInvoiceAmount: 1247 },
    ],
    requiresServiceVerification: false,
    daysUntilExpiration: 18,
  },
  {
    id: 'ctr-004',
    vendorName: 'Slack Technologies',
    contractType: 'saas',
    description: 'Slack Pro — 25 seats annual',
    startDate: '2024-01-15',
    endDate: '2025-01-15',
    autoRenews: true,
    renewalNoticeDays: 30,
    totalContractValue: 4462.50,
    billingFrequency: 'annual',
    lineItems: [
      { description: 'Slack Pro per seat', unit: 'per seat/year', unitPrice: 178.50, maxQuantity: 25 },
    ],
    linkedInvoiceIds: ['inv-006'],
    yearOverYear: [
      { year: 2022, totalSpend: 3750, invoiceCount: 1, avgInvoiceAmount: 3750 },
      { year: 2023, totalSpend: 4125, invoiceCount: 1, avgInvoiceAmount: 4125 },
      { year: 2024, totalSpend: 4462.50, invoiceCount: 1, avgInvoiceAmount: 4462.50 },
    ],
    requiresServiceVerification: false,
    daysUntilExpiration: 36,
  },
];

export const MOCK_POLICIES: InsurancePolicy[] = [
  {
    id: 'pol-001',
    carrier: 'Hiscox',
    policyNumber: 'HX-2024-GL-88421',
    policyType: 'general_liability',
    premium: 2100,
    billingFrequency: 'annual',
    effectiveDate: '2024-01-01',
    expirationDate: '2025-01-01',
    status: 'expiring_soon',
    daysUntilExpiration: 18,
    coverageItems: [
      { type: 'General Liability', limit: 1000000, deductible: 2500, description: 'Per occurrence' },
      { type: 'Products & Completed Ops', limit: 2000000, deductible: 2500, description: 'Aggregate' },
      { type: 'Personal & Advertising Injury', limit: 1000000, deductible: 0, description: 'Per occurrence' },
    ],
    aiSummary: 'Your general liability policy covers bodily injury and property damage claims from third parties up to $1M per occurrence. The aggregate limit is $2M. Note: this policy does NOT cover professional errors, cyber incidents, or employee injuries — you need separate policies for those.',
    gapsDetected: ['No cyber liability coverage', 'No professional liability coverage'],
    yearOverYearPremiums: [
      { year: 2022, premium: 1650 },
      { year: 2023, premium: 1890 },
      { year: 2024, premium: 2100 },
    ],
    alternativeQuotes: [
      { carrier: 'Coalition', premium: 1800, coverageMatch: 98, savings: 300, rating: 'A', notes: 'Includes basic cyber coverage. Highly rated for SMBs.' },
      { carrier: 'Next Insurance', premium: 1920, coverageMatch: 95, savings: 180, rating: 'A-', notes: 'Instant certificate of insurance. Good for contractors.' },
      { carrier: 'Thimble', premium: 2050, coverageMatch: 92, savings: 50, rating: 'B+', notes: 'Flexible monthly billing available.' },
    ],
    switchPaperworkReady: true,
  },
  {
    id: 'pol-002',
    carrier: 'Travelers',
    policyNumber: 'TRV-2024-WC-33901',
    policyType: 'workers_comp',
    premium: 4800,
    billingFrequency: 'annual',
    effectiveDate: '2024-03-01',
    expirationDate: '2025-03-01',
    status: 'active',
    daysUntilExpiration: 78,
    coverageItems: [
      { type: "Workers' Compensation", limit: 0, deductible: 0, description: 'Statutory limits — all states' },
      { type: "Employers' Liability", limit: 500000, deductible: 0, description: 'Per accident' },
    ],
    aiSummary: "Your workers' comp policy meets statutory requirements for all states where you operate. Employers' liability is set at $500K per accident, which is standard for your employee count. Premium is calculated on payroll — ensure you report accurate payroll at audit time to avoid surprises.",
    gapsDetected: [],
    yearOverYearPremiums: [
      { year: 2022, premium: 4200 },
      { year: 2023, premium: 4500 },
      { year: 2024, premium: 4800 },
    ],
    switchPaperworkReady: false,
  },
  {
    id: 'pol-003',
    carrier: 'Chubb',
    policyNumber: 'CHB-2024-CYB-77102',
    policyType: 'cyber',
    premium: 3600,
    billingFrequency: 'annual',
    effectiveDate: '2024-06-01',
    expirationDate: '2025-06-01',
    status: 'active',
    daysUntilExpiration: 163,
    coverageItems: [
      { type: 'Data Breach Response', limit: 500000, deductible: 5000, description: 'Notification, credit monitoring, PR' },
      { type: 'Cyber Extortion / Ransomware', limit: 250000, deductible: 5000, description: 'Ransom payment + response' },
      { type: 'Business Interruption', limit: 250000, deductible: 10000, description: '72-hour waiting period' },
      { type: 'Network Security Liability', limit: 500000, deductible: 5000, description: 'Third-party claims' },
    ],
    aiSummary: 'Your cyber policy provides solid coverage for data breaches and ransomware. The $250K ransomware limit may be low given current threat landscape — average ransomware demand for SMBs is $200K+. Consider increasing to $500K at next renewal. Business interruption has a 72-hour deductible which is standard.',
    gapsDetected: [],
    yearOverYearPremiums: [
      { year: 2023, premium: 2800 },
      { year: 2024, premium: 3600 },
    ],
    switchPaperworkReady: false,
  },
];

export const MOCK_RENEWALS: Renewal[] = [
  {
    id: 'ren-001',
    vendorName: 'Hiscox (General Liability)',
    type: 'insurance',
    renewalDate: '2025-01-01',
    daysUntilRenewal: 18,
    currentCost: 2100,
    autoRenews: true,
    noticePeriodDays: 30,
    status: 'action_required',
    policyId: 'pol-001',
    alternativeAvailable: true,
    potentialSavings: 300,
    notes: 'Coalition quote saves $300/yr with better coverage. Paperwork ready.',
  },
  {
    id: 'ren-002',
    vendorName: 'Apex IT Solutions',
    type: 'contract',
    renewalDate: '2024-12-31',
    daysUntilRenewal: 18,
    currentCost: 48000,
    autoRenews: true,
    noticePeriodDays: 60,
    status: 'action_required',
    contractId: 'ctr-001',
    notes: 'Contract auto-renews Dec 31. Notice period has passed — contact vendor to renegotiate rate.',
  },
  {
    id: 'ren-003',
    vendorName: 'Salesforce',
    type: 'saas',
    renewalDate: '2024-12-31',
    daysUntilRenewal: 18,
    currentCost: 14964,
    autoRenews: true,
    noticePeriodDays: 30,
    status: 'action_required',
    contractId: 'ctr-003',
    alternativeAvailable: true,
    potentialSavings: 2400,
    notes: 'HubSpot CRM offers comparable features at $8,400/yr. Savings: $6,564.',
  },
  {
    id: 'ren-004',
    vendorName: 'Slack',
    type: 'saas',
    renewalDate: '2025-01-15',
    daysUntilRenewal: 36,
    currentCost: 4462.50,
    autoRenews: true,
    noticePeriodDays: 30,
    status: 'upcoming',
    contractId: 'ctr-004',
    notes: 'Auto-renews Jan 15. Review seat count — may be able to reduce to 20 seats.',
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    vendorName: 'Salesforce Inc.',
    invoiceId: 'inv-003',
    invoiceNumber: 'SF-INV-2024-1201',
    amount: 1247.00,
    dueDate: '2024-12-31',
    paymentMethod: 'ach',
    bankAccount: '****4821',
    routingNumber: '021000021',
    status: 'pending_approval',
    quickbooksStatus: 'synced',
    notes: 'Monthly recurring — no anomalies detected. Ready for approval.',
  },
  {
    id: 'pay-002',
    vendorName: 'WeWork',
    invoiceId: 'inv-004',
    invoiceNumber: 'WW-2024-DEC',
    amount: 3200.00,
    dueDate: '2025-01-01',
    paymentMethod: 'ach',
    bankAccount: '****4821',
    routingNumber: '021000021',
    status: 'pending_approval',
    quickbooksStatus: 'synced',
    notes: 'Monthly office rent. No anomalies.',
  },
  {
    id: 'pay-003',
    vendorName: 'Slack Technologies',
    invoiceId: 'inv-006',
    invoiceNumber: 'SLK-2024-ANN',
    amount: 4462.50,
    dueDate: '2025-01-15',
    paymentMethod: 'credit_card',
    status: 'pending_approval',
    quickbooksStatus: 'pending',
    notes: 'Annual renewal. Consider reducing seat count before approving.',
  },
];

export const MOCK_ALERTS: InboxAlert[] = [
  {
    id: 'alrt-001',
    priority: 'urgent',
    title: 'Cyber insurance expires in 18 days',
    subtitle: 'Hiscox policy — auto-renew at +14.6% increase. Coalition quote saves $300/yr. Paperwork ready.',
    amount: 2100,
    actionLabel: 'Review Quotes',
    secondaryActionLabel: 'View Policy',
    dismissed: false,
    createdAt: new Date().toISOString(),
    policyId: 'pol-001',
  },
  {
    id: 'alrt-002',
    priority: 'urgent',
    title: 'Duplicate invoice detected',
    subtitle: 'Arctic Snow Services — ASS-2024-082 matches paid invoice ASS-2024-079. Do not pay.',
    amount: 260,
    actionLabel: 'View Invoice',
    secondaryActionLabel: 'Dismiss',
    dismissed: false,
    createdAt: new Date().toISOString(),
    invoiceId: 'inv-002',
  },
  {
    id: 'alrt-003',
    priority: 'urgent',
    title: 'Contract overcharge — Apex IT',
    subtitle: 'Invoice APEX-2024-112 bills 42 hrs — contract caps at 40. Overcharge: $190.',
    amount: 4750,
    actionLabel: 'Review Invoice',
    secondaryActionLabel: 'Flag Vendor',
    dismissed: false,
    createdAt: new Date().toISOString(),
    invoiceId: 'inv-001',
  },
  {
    id: 'alrt-004',
    priority: 'urgent',
    title: 'Snowfall discrepancy — Arctic Snow',
    subtitle: 'Vendor claims 4.2" on Dec 12. NOAA shows 2.8". You\'re being overcharged $65.',
    amount: 260,
    actionLabel: 'View Evidence',
    secondaryActionLabel: 'Dispute',
    dismissed: false,
    createdAt: new Date().toISOString(),
    invoiceId: 'inv-002',
  },
  {
    id: 'alrt-005',
    priority: 'review',
    title: 'Apex IT contract auto-renews in 18 days',
    subtitle: 'Annual value $48,000. Notice period has passed. Contact vendor to renegotiate.',
    amount: 48000,
    actionLabel: 'View Contract',
    secondaryActionLabel: 'Dismiss',
    dismissed: false,
    createdAt: new Date().toISOString(),
    contractId: 'ctr-001',
  },
  {
    id: 'alrt-006',
    priority: 'review',
    title: 'Incomplete invoice — Midwest Plumbing',
    subtitle: 'Missing: amount, due date, line items. Auto-response sent Dec 14.',
    actionLabel: 'View Invoice',
    secondaryActionLabel: 'Resend Request',
    dismissed: false,
    createdAt: new Date().toISOString(),
    invoiceId: 'inv-005',
  },
  {
    id: 'alrt-007',
    priority: 'review',
    title: 'Salesforce renewal — alternative available',
    subtitle: 'HubSpot CRM offers comparable features at $8,400/yr. Potential savings: $6,564.',
    amount: 14964,
    actionLabel: 'Compare Options',
    secondaryActionLabel: 'Dismiss',
    dismissed: false,
    createdAt: new Date().toISOString(),
    contractId: 'ctr-003',
  },
  {
    id: 'alrt-008',
    priority: 'info',
    title: '3 invoices ready for approval',
    subtitle: 'Salesforce ($1,247), WeWork ($3,200), Slack ($4,462.50) — all verified, no anomalies.',
    amount: 8909.50,
    actionLabel: 'Review Payments',
    dismissed: false,
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_SUMMARY: AppSummary = {
  pendingApprovals: 3,
  anomaliesDetected: 5,
  renewalsDueSoon: 3,
  coverageGaps: 2,
  totalPayableThisWeek: 8909.50,
  aiScansToday: 47,
  monthlySavingsIdentified: 1055,
};

// ─── Order Automation Mock Data ───────────────────────────────────────────────

export const MOCK_ORDERS: DeliveryOrder[] = [
  {
    id: 'ord-001',
    bolNumber: 'TB05866188',
    status: 'pending_approval',
    source: 'gmail',
    rawEmailSubject: 'Delivery Order – BOL TB05866188 – Sarcona to Kering Eyewear',
    receivedDate: '2026-03-11T04:41:00Z',
    extractionConfidence: 0.96,
    shipper: {
      name: 'Sarcona Management Inc.',
      locationCode: 'EAJ',
      address: '10 North Ave East',
      city: 'Elizabeth',
      state: 'NJ',
      zip: '07201',
      country: 'US',
      phone: '+1 973-466-0026',
    },
    consignee: {
      name: 'Kering Eyewear USA Inc.',
      address: '885 Centennial Ave',
      city: 'Piscataway',
      state: 'NJ',
      zip: '08854',
      country: 'US',
    },
    thirdPartyBillTo: {
      name: 'DSV / Ex Works Inc.',
      address: '100 Walnut Ave, Suite 310',
      city: 'Clark',
      state: 'NJ',
      zip: '07066',
      country: 'US',
    },
    pickupReady: '2026-03-11T04:41:00Z',
    pickupClose: '2026-03-11T11:44:00Z',
    projectedDelivery: '2026-03-12T01:00:00Z',
    cargoItems: [
      { description: 'Metal Optical Frame', pieces: 14, weightLbs: 505, weightKg: 229.1, hazmat: false },
    ],
    totalPieces: 14,
    totalWeightLbs: 505,
    currency: 'USD',
    carrierQuoteRef: 'RATE',
    billingPortal: 'www.exworksinc.com',
    references: [
      { label: 'File #', value: 'SMNL0210258' },
      { label: 'MWB', value: 'MNL0210258' },
      { label: 'HWB', value: 'MNL0210258' },
    ],
    carrierContact: { name: 'Alice Kearney', email: 'alice.kearney@dsv.com', phone: '732-850-8000' },
    anomalies: [
      { id: 'oa-001', type: 'missing_rate', severity: 'high', description: 'Carrier quote reference shows "RATE" — no confirmed rate provided. Confirm before dispatching.', resolved: false },
      { id: 'oa-002', type: 'third_party_billing', severity: 'medium', description: 'Bill-to party is DSV / Ex Works Inc., not shipper or consignee. Confirm billing authorization.', resolved: false },
    ],
    missingFields: ['Quoted Rate', 'Freight Class'],
    autoResponseSent: true,
    aiNotes: 'Pickup window is 7 hours (04:41–11:44). Projected delivery ~20 hours after pickup close — feasible for NJ–NJ lane. Rate confirmation is blocking dispatch.',
  },
  {
    id: 'ord-002',
    bolNumber: 'TB05871234',
    status: 'confirmed',
    source: 'outlook',
    rawEmailSubject: 'New Delivery Order – BOL TB05871234',
    receivedDate: '2026-03-10T09:15:00Z',
    extractionConfidence: 0.98,
    shipper: { name: 'Apex Logistics Hub', address: '450 Industrial Blvd', city: 'Newark', state: 'NJ', zip: '07105', country: 'US', phone: '+1 973-555-0100' },
    consignee: { name: 'Metro Distribution Center', address: '2200 Commerce Drive', city: 'Edison', state: 'NJ', zip: '08817', country: 'US' },
    pickupReady: '2026-03-10T08:00:00Z',
    pickupClose: '2026-03-10T14:00:00Z',
    projectedDelivery: '2026-03-10T18:00:00Z',
    cargoItems: [{ description: 'Consumer Electronics – Boxed Units', pieces: 48, weightLbs: 1200, weightKg: 544.3, freightClass: '70', hazmat: false }],
    totalPieces: 48,
    totalWeightLbs: 1200,
    quotedRate: 875,
    currency: 'USD',
    carrierQuoteRef: 'QT-2026-0310-A',
    references: [{ label: 'PO #', value: 'PO-88421' }, { label: 'Ref #', value: 'APX-NJ-0310' }],
    carrierContact: { name: 'James Ortega', email: 'j.ortega@apexlogistics.com', phone: '973-555-0101' },
    anomalies: [],
    aiNotes: 'All fields complete. Rate confirmed at $875. NJ–NJ same-day delivery. No anomalies detected.',
  },
  {
    id: 'ord-003',
    bolNumber: 'TB05869900',
    status: 'flagged',
    source: 'gmail',
    rawEmailSubject: 'FWD: Pickup Request – Urgent',
    receivedDate: '2026-03-11T07:30:00Z',
    extractionConfidence: 0.81,
    shipper: { name: 'Global Freight Partners', address: '88 Harbor Way', city: 'Bayonne', state: 'NJ', zip: '07002', country: 'US' },
    consignee: { name: 'TechSource Warehousing', address: '300 Technology Drive', city: 'Parsippany', state: 'NJ', zip: '07054', country: 'US' },
    pickupReady: '2026-03-11T09:00:00Z',
    pickupClose: '2026-03-11T09:45:00Z',
    projectedDelivery: '2026-03-11T17:00:00Z',
    cargoItems: [{ description: 'Server Equipment – Fragile', pieces: 6, weightLbs: 890, weightKg: 403.9, freightClass: '85', hazmat: false, specialInstructions: 'Keep upright. No stacking.' }],
    totalPieces: 6,
    totalWeightLbs: 890,
    quotedRate: 1450,
    currency: 'USD',
    references: [{ label: 'BOL Ref', value: 'GFP-2026-0311' }],
    anomalies: [
      { id: 'oa-003', type: 'tight_window', severity: 'high', description: 'Pickup window is only 45 minutes (09:00–09:45). Operationally infeasible for most carriers.', resolved: false },
      { id: 'oa-004', type: 'address_unverified', severity: 'medium', description: 'Consignee address could not be verified against USPS database. Confirm before dispatch.', resolved: false },
    ],
    aiNotes: 'Extraction confidence 81% — forwarded email chain with partial formatting. Pickup window critically tight at 45 minutes.',
  },
  {
    id: 'ord-004',
    bolNumber: 'TB05872500',
    status: 'dispatched',
    source: 'gmail',
    rawEmailSubject: 'Delivery Order Confirmation – BOL TB05872500',
    receivedDate: '2026-03-09T14:00:00Z',
    extractionConfidence: 0.99,
    shipper: { name: 'Prestige Auto Parts', address: '1 Industrial Court', city: 'Linden', state: 'NJ', zip: '07036', country: 'US', phone: '+1 908-555-0200' },
    consignee: { name: 'AutoZone Distribution', address: '500 Route 1 South', city: 'Woodbridge', state: 'NJ', zip: '07095', country: 'US' },
    pickupReady: '2026-03-09T13:00:00Z',
    pickupClose: '2026-03-09T17:00:00Z',
    projectedDelivery: '2026-03-09T20:00:00Z',
    cargoItems: [{ description: 'Automotive Brake Components', pieces: 32, weightLbs: 2400, weightKg: 1088.6, freightClass: '55', hazmat: false }],
    totalPieces: 32,
    totalWeightLbs: 2400,
    quotedRate: 620,
    currency: 'USD',
    carrierQuoteRef: 'QT-2026-0309-B',
    references: [{ label: 'PO #', value: 'AZ-NJ-9920' }],
    carrierContact: { name: 'Maria Santos', email: 'm.santos@prestigeauto.com', phone: '908-555-0201' },
    anomalies: [],
    aiNotes: 'Clean order. All fields verified. Dispatched on time.',
  },
];
