// ─── Pattern Detection Demo Data ─────────────────────────────────────────────
// Rich mock data that demonstrates all 10 alert types in the pattern engine.
// Includes property-mapped invoices, vendor history, and service events.

import { Invoice } from './types';

// Property map: invoiceId → property name
export const PROPERTY_MAP: Record<string, string> = {
  'inv-001': 'General Operations',
  'inv-002': '412 Oak Street',
  'inv-003': '412 Oak Street',
  'inv-004': '123 Main Street',
  'inv-005': '123 Main Street',
  'inv-006': '123 Main Street',
  'inv-007': '89 Cedar Avenue',
  'inv-008': '89 Cedar Avenue',
  'inv-009': 'General Operations',
  'inv-010': 'General Operations',
  'inv-011': '412 Oak Street',
  'inv-012': '412 Oak Street',
  'inv-013': '412 Oak Street',
  'inv-014': '55 Maple Drive',
  'inv-015': '55 Maple Drive',
  'inv-016': 'General Operations',
  'inv-017': 'General Operations',
  'inv-018': '89 Cedar Avenue',
  'inv-019': '89 Cedar Avenue',
  'inv-020': '123 Main Street',
};

// Extended invoice history for pattern detection demo
export const PATTERN_INVOICES: Invoice[] = [
  // ── 123 Main Street: Repeated plumbing (Joe's Plumbing visits 3x in 35 days)
  {
    id: 'inv-004',
    vendorName: "Joe's Plumbing",
    vendorEmail: 'invoices@joesplumbing.com',
    invoiceNumber: 'JP-2026-001',
    amount: 450,
    dueDate: '2026-02-15',
    receivedDate: '2026-01-03',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.98,
    lineItems: [{ description: 'Emergency drain clearing — clogged main line', quantity: 1, unitPrice: 450, total: 450, confidence: 0.98 }],
    anomalies: [],
    notes: 'property: 123 Main Street',
  },
  {
    id: 'inv-005',
    vendorName: "Joe's Plumbing",
    vendorEmail: 'invoices@joesplumbing.com',
    invoiceNumber: 'JP-2026-008',
    amount: 520,
    dueDate: '2026-02-28',
    receivedDate: '2026-01-24',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.97,
    lineItems: [{ description: 'Drain clearing — recurring clog, same main line', quantity: 1, unitPrice: 520, total: 520, confidence: 0.97 }],
    anomalies: [],
    notes: 'property: 123 Main Street',
  },
  {
    id: 'inv-006',
    vendorName: "Joe's Plumbing",
    vendorEmail: 'invoices@joesplumbing.com',
    invoiceNumber: 'JP-2026-015',
    amount: 490,
    dueDate: '2026-03-10',
    receivedDate: '2026-02-07',
    status: 'pending',
    source: 'gmail',
    extractionConfidence: 0.99,
    lineItems: [{ description: 'Drain clearing — third visit, clog returned', quantity: 1, unitPrice: 490, total: 490, confidence: 0.99 }],
    anomalies: [],
    notes: 'property: 123 Main Street',
  },
  {
    id: 'inv-020',
    vendorName: "Joe's Plumbing",
    vendorEmail: 'invoices@joesplumbing.com',
    invoiceNumber: 'JP-2025-089',
    amount: 380,
    dueDate: '2025-11-15',
    receivedDate: '2025-10-20',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.96,
    lineItems: [{ description: 'Pipe inspection and minor repair', quantity: 1, unitPrice: 380, total: 380, confidence: 0.96 }],
    anomalies: [],
    notes: 'property: 123 Main Street',
  },

  // ── 412 Oak Street: High maintenance frequency (property risk)
  {
    id: 'inv-002',
    vendorName: 'Arctic Snow Services',
    vendorEmail: 'invoices@arcticsnow.com',
    invoiceNumber: 'ASS-2026-012',
    amount: 260,
    dueDate: '2026-02-20',
    receivedDate: '2026-01-13',
    status: 'flagged',
    source: 'gmail',
    extractionConfidence: 0.99,
    lineItems: [{ description: 'Snow removal — Jan 12 event (4.2" claimed)', quantity: 1, unitPrice: 260, total: 260, confidence: 0.99 }],
    anomalies: [],
    notes: 'property: 412 Oak Street',
  },
  {
    id: 'inv-011',
    vendorName: 'Metro HVAC Services',
    vendorEmail: 'billing@metrohvac.com',
    invoiceNumber: 'MH-2026-031',
    amount: 890,
    dueDate: '2026-02-01',
    receivedDate: '2026-01-05',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.96,
    lineItems: [{ description: 'HVAC repair — heat exchanger inspection and cleaning', quantity: 1, unitPrice: 890, total: 890, confidence: 0.96 }],
    anomalies: [],
    notes: 'property: 412 Oak Street',
  },
  {
    id: 'inv-012',
    vendorName: 'Metro HVAC Services',
    vendorEmail: 'billing@metrohvac.com',
    invoiceNumber: 'MH-2026-044',
    amount: 1240,
    dueDate: '2026-02-15',
    receivedDate: '2026-01-22',
    status: 'pending',
    source: 'gmail',
    extractionConfidence: 0.94,
    lineItems: [{ description: 'HVAC emergency repair — blower motor replacement', quantity: 1, unitPrice: 1240, total: 1240, confidence: 0.94 }],
    anomalies: [],
    notes: 'property: 412 Oak Street',
  },
  {
    id: 'inv-013',
    vendorName: 'Metro HVAC Services',
    vendorEmail: 'billing@metrohvac.com',
    invoiceNumber: 'MH-2026-052',
    amount: 760,
    dueDate: '2026-03-01',
    receivedDate: '2026-02-10',
    status: 'pending',
    source: 'gmail',
    extractionConfidence: 0.97,
    lineItems: [{ description: 'HVAC service call — thermostat and controls issue', quantity: 1, unitPrice: 760, total: 760, confidence: 0.97 }],
    anomalies: [],
    notes: 'property: 412 Oak Street',
  },
  {
    id: 'inv-003',
    vendorName: "Joe's Plumbing",
    vendorEmail: 'invoices@joesplumbing.com',
    invoiceNumber: 'JP-2026-022',
    amount: 340,
    dueDate: '2026-03-05',
    receivedDate: '2026-02-18',
    status: 'pending',
    source: 'gmail',
    extractionConfidence: 0.95,
    lineItems: [{ description: 'Bathroom leak repair — unit 2B', quantity: 1, unitPrice: 340, total: 340, confidence: 0.95 }],
    anomalies: [],
    notes: 'property: 412 Oak Street',
  },

  // ── 89 Cedar Avenue: Vendor price increase (Metro HVAC)
  {
    id: 'inv-007',
    vendorName: 'Metro HVAC Services',
    vendorEmail: 'billing@metrohvac.com',
    invoiceNumber: 'MH-2025-088',
    amount: 620,
    dueDate: '2025-10-15',
    receivedDate: '2025-09-20',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.98,
    lineItems: [{ description: 'HVAC seasonal tune-up and filter replacement', quantity: 1, unitPrice: 620, total: 620, confidence: 0.98 }],
    anomalies: [],
    notes: 'property: 89 Cedar Avenue',
  },
  {
    id: 'inv-008',
    vendorName: 'Metro HVAC Services',
    vendorEmail: 'billing@metrohvac.com',
    invoiceNumber: 'MH-2025-102',
    amount: 640,
    dueDate: '2025-12-10',
    receivedDate: '2025-11-15',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.97,
    lineItems: [{ description: 'HVAC winter prep service', quantity: 1, unitPrice: 640, total: 640, confidence: 0.97 }],
    anomalies: [],
    notes: 'property: 89 Cedar Avenue',
  },
  {
    id: 'inv-018',
    vendorName: 'Metro HVAC Services',
    vendorEmail: 'billing@metrohvac.com',
    invoiceNumber: 'MH-2026-018',
    amount: 980,
    dueDate: '2026-02-28',
    receivedDate: '2026-02-01',
    status: 'flagged',
    source: 'gmail',
    extractionConfidence: 0.96,
    lineItems: [{ description: 'HVAC spring inspection — rate increase applied', quantity: 1, unitPrice: 980, total: 980, confidence: 0.96 }],
    anomalies: [
      {
        id: 'ano-hvac-01',
        type: 'price_increase',
        severity: 'medium',
        description: 'Invoice 53% above historical average ($630 avg → $980)',
        expectedValue: 630,
        actualValue: 980,
        percentageVariance: 55.6,
        recommendation: 'Contact Metro HVAC to confirm rate change. Request itemized breakdown.',
      }
    ],
    notes: 'property: 89 Cedar Avenue',
  },
  {
    id: 'inv-019',
    vendorName: 'GreenScape Landscaping',
    vendorEmail: 'billing@greenscape.com',
    invoiceNumber: 'GS-2026-011',
    amount: 2100,
    dueDate: '2026-03-15',
    receivedDate: '2026-02-20',
    status: 'flagged',
    source: 'gmail',
    extractionConfidence: 0.95,
    lineItems: [{ description: 'Monthly landscaping service — February', quantity: 1, unitPrice: 2100, total: 2100, confidence: 0.95 }],
    anomalies: [
      {
        id: 'ano-gs-01',
        type: 'price_increase',
        severity: 'high',
        description: 'Invoice $1,200 above typical monthly rate ($900)',
        expectedValue: 900,
        actualValue: 2100,
        percentageVariance: 133,
        recommendation: 'Request itemized breakdown. Typical monthly rate is $900.',
      }
    ],
    notes: 'property: 89 Cedar Avenue',
  },

  // ── General Operations: SaaS / IT vendor history
  {
    id: 'inv-001',
    vendorName: 'Apex IT Solutions',
    vendorEmail: 'billing@apexit.com',
    invoiceNumber: 'APEX-2026-112',
    amount: 4750,
    dueDate: '2026-02-28',
    receivedDate: '2026-02-10',
    status: 'flagged',
    source: 'gmail',
    extractionConfidence: 0.97,
    contractId: 'ctr-001',
    previousAmount: 4000,
    lineItems: [
      { description: 'Managed IT Support (42 hrs @ $95/hr)', quantity: 42, unitPrice: 95, total: 3990, contractedPrice: 95, variance: 190, confidence: 0.98 },
      { description: 'Emergency On-site Visit', quantity: 1, unitPrice: 760, total: 760, contractedPrice: 0, variance: 760, confidence: 0.94 },
    ],
    anomalies: [
      {
        id: 'ano-001',
        type: 'contract_mismatch',
        severity: 'high',
        description: 'Invoice bills 42 hours — contract caps at 40 hrs/month. Overcharge: $190.',
        expectedValue: 4000,
        actualValue: 4750,
        percentageVariance: 18.75,
        recommendation: 'Request credit memo for 2 excess hours ($190).',
      },
    ],
    notes: 'property: General Operations',
  },
  {
    id: 'inv-009',
    vendorName: 'Apex IT Solutions',
    vendorEmail: 'billing@apexit.com',
    invoiceNumber: 'APEX-2025-098',
    amount: 4000,
    dueDate: '2025-12-28',
    receivedDate: '2025-12-05',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.98,
    contractId: 'ctr-001',
    lineItems: [
      { description: 'Managed IT Support (40 hrs @ $95/hr)', quantity: 40, unitPrice: 95, total: 3800, confidence: 0.99 },
      { description: 'Monthly monitoring fee', quantity: 1, unitPrice: 200, total: 200, confidence: 0.99 },
    ],
    anomalies: [],
    notes: 'property: General Operations',
  },
  {
    id: 'inv-010',
    vendorName: 'Apex IT Solutions',
    vendorEmail: 'billing@apexit.com',
    invoiceNumber: 'APEX-2025-085',
    amount: 4000,
    dueDate: '2025-11-28',
    receivedDate: '2025-11-05',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.98,
    contractId: 'ctr-001',
    lineItems: [
      { description: 'Managed IT Support (40 hrs @ $95/hr)', quantity: 40, unitPrice: 95, total: 3800, confidence: 0.99 },
      { description: 'Monthly monitoring fee', quantity: 1, unitPrice: 200, total: 200, confidence: 0.99 },
    ],
    anomalies: [],
    notes: 'property: General Operations',
  },

  // ── 55 Maple Drive: Normal activity (for portfolio comparison baseline)
  {
    id: 'inv-014',
    vendorName: 'CleanPro Services',
    vendorEmail: 'billing@cleanpro.com',
    invoiceNumber: 'CP-2026-022',
    amount: 380,
    dueDate: '2026-02-28',
    receivedDate: '2026-02-01',
    status: 'approved',
    source: 'gmail',
    extractionConfidence: 0.99,
    lineItems: [{ description: 'Monthly janitorial service — February', quantity: 1, unitPrice: 380, total: 380, confidence: 0.99 }],
    anomalies: [],
    notes: 'property: 55 Maple Drive',
  },
  {
    id: 'inv-015',
    vendorName: 'GreenScape Landscaping',
    vendorEmail: 'billing@greenscape.com',
    invoiceNumber: 'GS-2026-008',
    amount: 900,
    dueDate: '2026-02-15',
    receivedDate: '2026-01-20',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.98,
    lineItems: [{ description: 'Monthly landscaping — January', quantity: 1, unitPrice: 900, total: 900, confidence: 0.98 }],
    anomalies: [],
    notes: 'property: 55 Maple Drive',
  },

  // ── General Operations: SaaS subscriptions
  {
    id: 'inv-016',
    vendorName: 'Slack Technologies',
    vendorEmail: 'billing@slack.com',
    invoiceNumber: 'SLACK-2026-Q1',
    amount: 1620,
    dueDate: '2026-03-31',
    receivedDate: '2026-03-01',
    status: 'pending',
    source: 'gmail',
    extractionConfidence: 0.99,
    lineItems: [{ description: 'Slack Pro — quarterly subscription (Q1 2026)', quantity: 1, unitPrice: 1620, total: 1620, confidence: 0.99 }],
    anomalies: [],
    notes: 'property: General Operations',
  },
  {
    id: 'inv-017',
    vendorName: 'Slack Technologies',
    vendorEmail: 'billing@slack.com',
    invoiceNumber: 'SLACK-2025-Q4',
    amount: 1240,
    dueDate: '2025-12-31',
    receivedDate: '2025-12-01',
    status: 'paid',
    source: 'gmail',
    extractionConfidence: 0.99,
    lineItems: [{ description: 'Slack Pro — quarterly subscription (Q4 2025)', quantity: 1, unitPrice: 1240, total: 1240, confidence: 0.99 }],
    anomalies: [],
    notes: 'property: General Operations',
  },
];

// Savings detected from existing anomalies in the base mock data
export const SAVINGS_FROM_ANOMALIES = {
  duplicatesPrevented: 2,
  contractMismatchesCaught: 1,
  priceIncreasesChallenged: 2,
  totalSavingsDetected: 4820, // $190 overcharge + $1,000 snow mismatch + $750 HVAC increase + $2,880 landscaping anomaly
};
